email = "ryan.chris.smith.com"
land = "Ouray, Colorado"
car = "Toyota"
age = 19
area_code = 303
street_address = 5104
height = 6.1
goals_per_game = 1.33
avg_distance = 7.2
mowed_lawn = false
works_home = false
green = true
